<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <OutputType>Library</OutputType>
    <AssemblyName>UI.Validation.Library</AssemblyName>
    <RootNamespace>Vodafone.Robotics.UiValidation</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\ActivitiesMetadata.json" />
    <EmbeddedResource Include="Resources\ActivitiesMetadata.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Activities.ViewModels" Version="1.20260609.1" />
    <PackageReference Include="UiPath.Activities.Api" Version="24.10.1" PrivateAssets="all" />
    <PackageReference Include="UiPath.Workflow" Version="6.0.0-20240401-07" PrivateAssets="all" />
    <PackageReference Include="UiPath.UIAutomation.Activities" Version="24.10.13" />
  </ItemGroup>
</Project>
