<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RestoreAdditionalProjectSources>$(MSBuildThisFileDirectory)..\..\artifacts\packages</RestoreAdditionalProjectSources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vodafone.Robotics.UI.Validation.Activities" Version="2.0.0" />
    <PackageReference Include="UiPath.Activities.Api" Version="24.10.1" PrivateAssets="all" />
    <PackageReference Include="UiPath.Workflow" Version="6.0.0-20240401-07" PrivateAssets="all" />
  </ItemGroup>
</Project>
